---
name: terraform pre-commit
on:
  pull_request:

permissions:
  contents: read

jobs:
  pre-commit:
    uses: flufi-io/workflows/.github/workflows/terraform_precommit.yaml@main
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit
